name: Dupligit Bot

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  check-duplicate:
    if: github.event_name == 'issues'
    runs-on: ubuntu-latest
    steps:
      - name: Run Dupligit Check
        uses: CS453-Group4/Dupligit@v1.0.3
        with:
          mode: check
          issue-title: ${{ github.event.issue.title }}
          issue-number: ${{ github.event.issue.number }}
          repo: ${{ github.repository }}

  mark-duplicate:
    if: |
      github.event_name == 'issue_comment' &&
      contains(github.event.comment.body, '/mark-duplicate')
    runs-on: ubuntu-latest
    steps:
      - name: Run Dupligit Mark
        uses: CS453-Group4/Dupligit@v1.0.3
        with:
          mode: mark
          issue-body: ${{ github.event.comment.body }}
          issue-number: ${{ github.event.issue.number }}
          comment-author: ${{ github.event.comment.user.login }}
          repo: ${{ github.repository }}
